#!/bin/sh

set -eu

CONFIG_MANAGER="/usr/bin/config-manager"
OUTPUT_DIR="/etc/klipper/config/klipper-readonly"
OUTPUT_FILE="${OUTPUT_DIR}/_vars.cfg"

get_config_value() {
	"${CONFIG_MANAGER}" klipper "$1"
}

sync_camera_led_to_chamber_led=$(get_config_value sync_camera_led_to_chamber_led)
camera_led_default_on=$(get_config_value camera_led_default_on)
heatsoak=$(get_config_value heatsoak)
adaptive_mesh=$(get_config_value adaptive_mesh)
adaptive_purge=$(get_config_value adaptive_purge)
nozzle_z_homing=$(get_config_value nozzle_z_homing)
z_ideal_lifting_distance=$(get_config_value z_ideal_lifting_distance)
full_calibrate_hotend_temperature=$(get_config_value full_calibrate_hotend_temperature)
full_calibrate_bed_temperature=$(get_config_value full_calibrate_bed_temperature)
bypass_calibration=$(get_config_value bypass_calibration)
load_skew_profile=$(get_config_value load_skew_profile)
if $(echo "$load_skew_profile" | tr '[:upper:]' '[:lower:]'); then
	skew_profile_name=$(get_config_value skew_profile_name)
else
        #if someone has set load_skew_profile to false and also deleted skew_profile_name,
        #provide a dummy value since we are set -eu
        skew_profile_name="undefined"
fi

mkdir -p "${OUTPUT_DIR}"

cat > "${OUTPUT_FILE}" <<EOF
# Generated on startup from cosmos.conf
# Do not edit this file directly. Instead, edit cosmos.conf and reboot to apply changes.

[gcode_macro _COSMOS_SETTINGS]
variable_sync_camera_led_to_chamber_led: ${sync_camera_led_to_chamber_led}
variable_camera_led_default_on: ${camera_led_default_on}
variable_heatsoak: ${heatsoak}
variable_adaptive_mesh: ${adaptive_mesh}
variable_adaptive_purge: ${adaptive_purge}
variable_nozzle_z_homing: ${nozzle_z_homing}
variable_z_ideal_lifting_distance: ${z_ideal_lifting_distance}
variable_full_calibrate_hotend_temperature: ${full_calibrate_hotend_temperature}
variable_full_calibrate_bed_temperature: ${full_calibrate_bed_temperature}
variable_bypass_calibration: ${bypass_calibration}
variable_load_skew_profile: ${load_skew_profile}
variable_skew_profile_name: '"$skew_profile_name"'

gcode:

EOF

