#!/bin/sh

set -eu

CONFIG_MANAGER="/usr/bin/config-manager"
OUTPUT_DIR="/etc/klipper/config/klipper-readonly"
OUTPUT_FILE="${OUTPUT_DIR}/_vars.cfg"
EXTRAS_OUTPUT_FILE="${OUTPUT_DIR}/zextras.cfg"
MOONRAKER_UPDATE_FILE="/etc/klipper/config/moonraker-readonly/zupdate.conf"

get_config_value() {
	"${CONFIG_MANAGER}" klipper "$1"
}

sync_camera_led_to_chamber_led=$(get_config_value sync_camera_led_to_chamber_led)
camera_led_default_on=$(get_config_value camera_led_default_on)
heatsoak=$(get_config_value heatsoak)
adaptive_mesh=$(get_config_value adaptive_mesh)
adaptive_purge=$(get_config_value adaptive_purge)
unload_after_print=$(get_config_value unload_after_print)
clean_nozzle_after_print=$(get_config_value clean_nozzle_after_print)
nozzle_z_homing=$(get_config_value nozzle_z_homing)
z_ideal_lifting_distance=$(get_config_value z_ideal_lifting_distance)
full_calibrate_hotend_temperature=$(get_config_value full_calibrate_hotend_temperature)
full_calibrate_bed_temperature=$(get_config_value full_calibrate_bed_temperature)
bypass_calibration=$(get_config_value bypass_calibration)
toolhead_led=$(get_config_value toolhead_led)
elegoo_canvas=$("${CONFIG_MANAGER}" extras elegoo_canvas)
check_for_updates=$("${CONFIG_MANAGER}" update check_for_updates)
release=$("${CONFIG_MANAGER}" update release)

mkdir -p "${OUTPUT_DIR}"

cat > "${OUTPUT_FILE}" <<EOF
# Generated on startup from cosmos.conf
# Do not edit this file directly. Instead, edit cosmos.conf and reboot to apply changes.

[gcode_macro _COSMOS_SETTINGS]
variable_sync_camera_led_to_chamber_led: ${sync_camera_led_to_chamber_led}
variable_camera_led_default_on: ${camera_led_default_on}
variable_heatsoak: ${heatsoak}
variable_adaptive_mesh: ${adaptive_mesh}
variable_adaptive_purge: ${adaptive_purge}
variable_unload_after_print: ${unload_after_print}
variable_clean_nozzle_after_print: ${clean_nozzle_after_print}
variable_nozzle_z_homing: ${nozzle_z_homing}
variable_z_ideal_lifting_distance: ${z_ideal_lifting_distance}
variable_full_calibrate_hotend_temperature: ${full_calibrate_hotend_temperature}
variable_full_calibrate_bed_temperature: ${full_calibrate_bed_temperature}
variable_bypass_calibration: ${bypass_calibration}
variable_toolhead_led: ${toolhead_led}
gcode:

EOF

cat > "${EXTRAS_OUTPUT_FILE}" <<EOF
# Generated on startup from cosmos.conf
# Do not edit this file directly. Instead, edit cosmos.conf and reboot to apply changes.

EOF

if [ "${elegoo_canvas}" = "True" ]; then
	echo "[include ../extras-readonly/canvas.cfg]" >> "${EXTRAS_OUTPUT_FILE}"
fi

cat > "${MOONRAKER_UPDATE_FILE}" <<EOF
# Generated on startup from cosmos.conf
# Do not edit this file directly. Instead, edit cosmos.conf and reboot to apply changes.

EOF

if [ "${check_for_updates}" = "True" ]; then
	echo "[update_manager cosmos]" >> "${MOONRAKER_UPDATE_FILE}"
	echo "type: swupdate" >> "${MOONRAKER_UPDATE_FILE}"
	echo "repo: OpenCentauri/cosmos" >> "${MOONRAKER_UPDATE_FILE}"
	echo "asset_name: cosmos-@MACHINE@.swu" >> "${MOONRAKER_UPDATE_FILE}"
	if [ "${release}" = "nightly" ]; then
		echo "channel: dev" >> "${MOONRAKER_UPDATE_FILE}"
	else
		echo "channel: stable" >> "${MOONRAKER_UPDATE_FILE}"
	fi
fi

