[ui]
screen_ui = grumpyscreen
web_ui = mainsail
screen_brightness = 100

[update]
release = stable

[klipper]
sync_camera_led_to_chamber_led = False
camera_led_default_on = True
bypass_calibration = False
full_calibrate_hotend_temperature = 250
full_calibrate_bed_temperature = 60