FROM crops/poky:ubuntu-22.04

USER root
RUN sed -i 's|http://archive.ubuntu.com|http://de.archive.ubuntu.com|g; s|http://security.ubuntu.com|http://de.archive.ubuntu.com|g' /etc/apt/sources.list && \
    apt-get update && apt-get install -y libclang-dev && rm -rf /var/lib/apt/lists/*
USER usersetup

WORKDIR /cosmos
