#!/bin/sh
### BEGIN INIT INFO
# Provides:          usb-ether-rescue
# Required-Start:    $local_fs $remote_fs $network
# Required-Stop:     $local_fs $remote_fs
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Boot-time USB-Ethernet DHCP bring-up (Class 217 recovery)
### END INIT INFO

case "$1" in
    start)
        /usr/sbin/usb-ether-rescue
        ;;
    stop|restart|force-reload|status)
        ;;
    *)
        echo "Usage: $0 {start|stop|restart|force-reload|status}"
        exit 1
        ;;
esac

exit 0
