#!/bin/sh
### BEGIN INIT INFO
# Provides:          klipper-firmware-dsp
# Required-Start:    $local_fs $remote_fs $network
# Required-Stop:     $local_fs $remote_fs $network
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Start OpenCentauri firmware
### END INIT INFO

REMOTEPROCFILE="/sys/class/remoteproc/remoteproc0/state"

set_gpio(){
    GPIO="$1"
    STATE="$2"

    echo $GPIO > /sys/class/gpio/export
    echo out > /sys/class/gpio/gpio$GPIO/direction
    echo $STATE > /sys/class/gpio/gpio$GPIO/value
    echo $GPIO > /sys/class/gpio/unexport
}

case "$1" in
    start)
        echo "Starting klipper-firmware-dsp..."
        echo start > $REMOTEPROCFILE
        ;;
    stop)
        echo "Stopping klipper-firmware-dsp..."
        echo stop > $REMOTEPROCFILE

        set_gpio 205 0 # heated bed PG13
        set_gpio 166 1 # stepper x enable PF6, active low
        set_gpio 143 1 # stepper y enable PE15, active low
        set_gpio 140 1 # stepper z enable PE12, active low
        set_gpio 44  0 # buzzer PB12
        set_gpio 207 0 # mainboard fan PG15
        set_gpio 111 0 # aux fan PD15
        set_gpio 113 0 # case fan PD17
        set_gpio 37  0 # case led PB5
        set_gpio 39  0 # case servo PB7
        ;;
    restart|force-reload)
        $0 stop
        sleep 1
        $0 start
        ;;
    status)
        echo "klipper-firmware-dsp is $(cat $REMOTEPROCFILE)"
        ;;
    *)
        echo "Usage: $0 {start|stop|restart|status}"
        exit 1
        ;;
esac

exit 0
