#@TYPE: Machine
#@NAME: Elegoo Centauri Carbon 2
#@DESCRIPTION: Machine configuration for the Elegoo Centauri Carbon 2, based on the Allwinner R528 CPU

require conf/machine/include/sun8i.inc

DEFAULTTUNE = "cortexa7thf-neon-vfpv4"

KERNEL_DEVICETREE = "allwinner/elegoo-centauri-carbon2.dtb"
KERNEL_IMAGETYPE = "zImage"
UBOOT_ENTRYPOINT = "0x43000000"
SERIAL_CONSOLES = "ttyS2,115200"
SERIAL_ADDR = "0x02500800"

UBOOT_MACHINE = "elegoo_centauri_carbon2_defconfig"
