#!/bin/bash
# OpenCentauri Docker Build Script

set -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_DIR="$(cd "$SCRIPT_DIR/../.." && pwd)"
BUILD_DIR="$REPO_DIR/build"
CACHE_DIR="$REPO_DIR/cache"

# Create directories
mkdir -p "$BUILD_DIR" "$CACHE_DIR"

echo "========================================"
echo "OpenCentauri Docker Build"
echo "========================================"
echo ""

# Build Docker image
echo "Building Docker image..."
docker build -t opencentauri-build "$SCRIPT_DIR"

echo ""
echo "Starting Docker container..."
echo ""

# Run Docker container with volume mounts
docker run --rm -i \
    -v "$REPO_DIR:/home/builder/opencentauri-repo" \
    -v "$CACHE_DIR:/home/builder/cache" \
    -w /home/builder/opencentauri-repo \
    opencentauri-build \
    /bin/bash -c '
        set -e
        echo ""
        echo "========================================"
        echo "Initializing Yocto Build Environment"
        echo "========================================"

        # Initialize submodules if not already done
        if [ ! -d "poky" ]; then
            echo "Initializing git submodules..."
            git submodule update --init --recursive
        fi

        # Source Yocto environment
        source poky/oe-init-build-env build

        # Create site.conf for bindgen cross-compilation (not in repo, auto-included by bitbake)
        cat > /home/builder/opencentauri-repo/build/conf/site.conf << 'SITECONF'
# Site-specific configuration (generated by Docker build.sh)
# This file is not in the repo and will not be committed.

# Bindgen cross-compilation support
# clang needs ARM sysroot for cross-compilation (asm/types.h)
export BINDGEN_EXTRA_CLANG_ARGS = "--sysroot=\${RECIPE_SYSROOT}"
SITECONF

        echo ""
        echo "========================================"
        echo "Starting BitBake Build"
        echo "========================================"
        echo ""

        # Build SWUpdate images (pass any arguments or build all)
        if [ -n "$1" ]; then
            bitbake "$@"
        else
            bitbake \
                opencentauri-upgrade \
                opencentauri-upgrade-hh-full \
                opencentauri-upgrade-hh-minimal
        fi

        echo ""
        echo "========================================"
        echo "Build Complete!"
        echo "========================================"
        echo ""
        echo "Images location: /home/builder/opencentauri-repo/build/tmp/deploy/images/elegoo-centauri-carbon1/"
        echo ""
        echo "SWUpdate Images:"
        ls -la /home/builder/opencentauri-repo/build/tmp/deploy/images/elegoo-centauri-carbon1/*.swu 2>/dev/null || true

        # Cleanup: remove site.conf
        rm -f /home/builder/opencentauri-repo/build/conf/site.conf
        echo "Cleaned up site.conf"
    ' -- "$@"
