#!/bin/sh

if [ ! -f "$1" ]; then
    echo "Usage: $0 path/to/update.swu"
    exit 1
fi

SWU_FILE=$(realpath "$1")
TEMP_DIR="/user-resource/.tmp"
mkdir -p "$TEMP_DIR"
cd "$TEMP_DIR"
cpio -i -u -F "$SWU_FILE" sw-description

stock_image="false"
if grep -qs "cosmos =" "$TEMP_DIR/sw-description"; then
    selection="cosmos"
elif grep -qs "awuboot" "$TEMP_DIR/sw-description"; then
    selection="stable"
    stock_image="true"
else
    selection="stable"
fi

rm -f "$TEMP_DIR/sw-description"

curr=$(fw_printenv systemAB_next | awk -F= '{ print $2 }' | tr -d '[:space:]')

if [[ "$curr" == "A" ]]; then
    boot_partition="now_A_next_B"
elif [[ "$curr" == "B" ]]; then
    boot_partition="now_B_next_A"
else
    exit 1
fi

echo "Installing $selection,$boot_partition"

set -e

readonly-config-reset

if [ "$stock_image" = "true" ]; then
    restore-mcu-firmware
fi

swupdate -v -i "$SWU_FILE" -e ${selection},${boot_partition}

if [ "$stock_image" = "true" ]; then
    fw_setenv bootcmd "run setargs_mmc boot_dsp0 boot_normal"
fi

sync

echo "Update finished, run 'reboot' to finalize"
