#!/bin/sh
### BEGIN INIT INFO
# Provides:          klipper-firmware-toolhead
# Required-Start:    $local_fs $remote_fs $network
# Required-Stop:     $local_fs $remote_fs $network
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Start OpenCentauri firmware
### END INIT INFO

FIRMWARE="/lib/firmware/klipper-toolhead.bin"
FIRMWARE_VERSION="/lib/firmware/klipper-toolhead.bin.ver"
KATAPULT_DEPLOYER="/lib/firmware/katapult-deployer-toolhead.bin"
INSTALLED_VERSION="/etc/toolhead.ver"
SERIALPORT="/dev/ttyS3"
GPIO="145"

update(){
    mcu-flasher --firmware $FIRMWARE --no-wait $SERIALPORT --cc2 --timeout 20 &
    FLASHER=$!
    sleep 1

    echo $GPIO > /sys/class/gpio/export
    echo out > /sys/class/gpio/gpio$GPIO/direction
    echo 0 > /sys/class/gpio/gpio$GPIO/value
    sleep 2
    echo 1 > /sys/class/gpio/gpio$GPIO/value
    echo $GPIO > /sys/class/gpio/unexport

    if wait $FLASHER; then
        cp $FIRMWARE_VERSION $INSTALLED_VERSION
        echo "Firmware flashed and version recorded."
    else
        echo "Firmware flash failed, version not updated."
        return 1
    fi
}

case "$1" in
    start)
        echo "Starting klipper-firmware-toolhead..."
        echo $GPIO > /sys/class/gpio/export
        echo out > /sys/class/gpio/gpio$GPIO/direction
        echo 1 > /sys/class/gpio/gpio$GPIO/value
        echo $GPIO > /sys/class/gpio/unexport
        sleep 1

        if [ -f "$INSTALLED_VERSION" ] && [ "$(cat $INSTALLED_VERSION)" == "$(cat $FIRMWARE_VERSION)" ]; then
            echo "Firmware is already up to date."
            exit 0
        else
            echo "Firmware version mismatch or not installed, flashing firmware..."
            PSPLASH_FIFO_DIR="/var/psplash" psplash-write "MSG Flashing toolhead. DO NOT POWER OFF"
            update
            PSPLASH_FIFO_DIR="/var/psplash" psplash-write "MSG  "
        fi
        ;;
    stop)
        echo "Stopping klipper-firmware-toolhead..."
        echo $GPIO > /sys/class/gpio/export
        echo out > /sys/class/gpio/gpio$GPIO/direction
        echo 0 > /sys/class/gpio/gpio$GPIO/value
        echo $GPIO > /sys/class/gpio/unexport
        ;;
    restart|force-reload)
        $0 stop
        sleep 2
        $0 start
        ;;
    status)
        echo $GPIO > /sys/class/gpio/export
        gpio_value=$(cat /sys/class/gpio/gpio$GPIO/value)
        echo $GPIO > /sys/class/gpio/unexport
        if [ "$gpio_value" = "1" ]; then
            echo "klipper-firmware-toolhead is running"
        else
            echo "klipper-firmware-toolhead is not running"
        fi
        ;;
    *)
        echo "Usage: $0 {start|stop|restart|status}"
        exit 1
        ;;
esac

exit 0
