#!/bin/sh
### BEGIN INIT INFO
# Provides:          klipper-firmware-dsp
# Required-Start:    $local_fs $remote_fs $network
# Required-Stop:     $local_fs $remote_fs $network
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Start OpenCentauri firmware
### END INIT INFO

REMOTEPROCFILE="/sys/class/remoteproc/remoteproc0/state"

set_gpio(){
    GPIO="$1"
    STATE="$2"

    echo $GPIO > /sys/class/gpio/export
    echo out > /sys/class/gpio/gpio$GPIO/direction
    echo $STATE > /sys/class/gpio/gpio$GPIO/value
    echo $GPIO > /sys/class/gpio/unexport
}

case "$1" in
    start)
        echo "Starting klipper-firmware-dsp..."
        echo start > $REMOTEPROCFILE
        ;;
    stop)
        echo "Stopping klipper-firmware-dsp..."
        echo stop > $REMOTEPROCFILE

        set_gpio 205 0 # heated bed PG13
        set_gpio 138 1 # stepper x enable PE10, active low
        set_gpio 143 1 # stepper y enable PE15, active low
        set_gpio 193 1 # stepper z enable PG1, active low
        set_gpio 197 0 # buzzer PG5
        set_gpio 208 0 # mainboard fan PG16
        set_gpio 209 0 # aux fan PG17
        set_gpio 210 0 # case fan PG18
        set_gpio 207 0 # case led PG15
        ;;
    restart|force-reload)
        $0 stop
        sleep 1
        $0 start
        ;;
    status)
        echo "klipper-firmware-dsp is $(cat $REMOTEPROCFILE)"
        ;;
    *)
        echo "Usage: $0 {start|stop|restart|status}"
        exit 1
        ;;
esac

exit 0
